sensors:

  breakbeam_0:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.35, 4.15, 0.95]
      rpy: [0, 0, pi]
  breakbeam_1:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.35, -0.05, 0.95]
      rpy: [0, 0, pi]
  breakbeam_2:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.35, -4.3, 0.95]
      rpy: [0, 0, pi]
  convey_camera_1:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [0, 3.1, 2.0]
      rpy: [pi, pi/2, 0]
  convey_camera_2:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [0, 1.0, 2.0]
      rpy: [pi, pi/2, 0]

  right_bins_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-2.286, 2.96, 1.8]
      rpy: [pi, pi/2, 0]

  left_bins_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-2.286, -2.96, 1.8]
      rpy: [pi, pi/2, 0]

  kts1_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-1.3, -5.8, 1.5]
      rpy: [pi, pi/2, pi/2]
  
  kts2_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-1.3, 5.8, 1.5]
      rpy: [pi, pi/2, -pi/2]
      
      
  station0_l_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-7.5, 1.3, 1.3]
      rpy: [pi, pi/2, -pi/2]

  station0_r_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-7.5, 4.8, 1.3]
      rpy: [pi, pi/2, -pi/2]

  station1_l_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-12.5,1.3, 1.3]
      rpy: [pi, pi/2, -pi/2]

  station1_r_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-12.5, 4.8, 1.3]
      rpy: [pi, pi/2, -pi/2]
      
  station2_r_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-12.5, -1.4, 1.3]
      rpy: [pi, pi/2, -pi/2]

  station2_l_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-12.5, -4.9, 1.3]
      rpy: [pi, pi/2, -pi/2]
      
  station3_r_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-7.5, -1.4, 1.3]
      rpy: [pi, pi/2, -pi/2]

  station3_l_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-7.5, -4.9, 1.3]
      rpy: [pi, pi/2, -pi/2]
  
